ui: Add dummpy / explanatory main function
This fixes regressions in the CI suite that fail otherwise unrelated
pull requests, probably due to nowadays stricter clippy errors (`cargo
+nightly clippy` previously failed with 'error[E0601]: `main` function
not found in crate `typed_html_tests`').